# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Api.Employees do
  @moduledoc """
  API calls for all endpoints tagged `Employees`.
  """

  alias MergeHRISClient.Connection
  import MergeHRISClient.RequestBuilder


  @doc """
  Creates an `Employee` object with the given values.

  ## Parameters

  - connection (MergeHRISClient.Connection): Connection to server
  - authorization (String.t): Should include 'Bearer ' followed by your production API Key.
  - x_account_token (String.t): Token identifying the end user.
  - opts (KeywordList): [optional] Optional parameters
    - :run_async (boolean()): Whether or not third-party updates should be run asynchronously.
    - :body (EmployeeRequest): 
  ## Returns

  {:ok, MergeHRISClient.Model.Employee.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec employees_create(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, MergeHRISClient.Model.Employee.t} | {:error, Tesla.Env.t}
  def employees_create(connection, authorization, x_account_token, opts \\ []) do
    optional_params = %{
      :"run_async" => :query,
      :body => :body
    }
    %{}
    |> method(:post)
    |> url("/employees")
    |> add_param(:headers, :"Authorization", authorization)
    |> add_param(:headers, :"X-Account-Token", x_account_token)
    |> add_optional_params(optional_params, opts)
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %MergeHRISClient.Model.Employee{}}
    ])
  end

  @doc """
  Returns a list of `Employee` objects.

  ## Parameters

  - connection (MergeHRISClient.Connection): Connection to server
  - authorization (String.t): Should include 'Bearer ' followed by your production API Key.
  - x_account_token (String.t): Token identifying the end user.
  - opts (KeywordList): [optional] Optional parameters
    - :company_id (String.t): If provided, will only return employees for this company.
    - :created_after (DateTime.t): If provided, will only return objects created after this datetime.
    - :created_before (DateTime.t): If provided, will only return objects created before this datetime.
    - :cursor (String.t): The pagination cursor value.
    - :expand (String.t): Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
    - :include_remote_data (boolean()): Whether to include the original data Merge fetched from the third-party to produce these models.
    - :include_sensitive_fields (boolean()): Whether to include sensetive fields (such as social security numbers) in the response.
    - :manager_id (String.t): If provided, will only return employees for this manager.
    - :modified_after (DateTime.t): If provided, will only return objects modified after this datetime.
    - :modified_before (DateTime.t): If provided, will only return objects modified before this datetime.
    - :page_size (integer()): Number of results to return per page.
    - :remote_id (String.t): The API provider's ID for the given object.
    - :team_id (String.t): If provided, will only return employees for this team.
    - :work_location_id (String.t): If provided, will only return employees for this location.
  ## Returns

  {:ok, MergeHRISClient.Model.PaginatedEmployeeList.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec employees_list(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, MergeHRISClient.Model.PaginatedEmployeeList.t} | {:error, Tesla.Env.t}
  def employees_list(connection, authorization, x_account_token, opts \\ []) do
    optional_params = %{
      :"company_id" => :query,
      :"created_after" => :query,
      :"created_before" => :query,
      :"cursor" => :query,
      :"expand" => :query,
      :"include_remote_data" => :query,
      :"include_sensitive_fields" => :query,
      :"manager_id" => :query,
      :"modified_after" => :query,
      :"modified_before" => :query,
      :"page_size" => :query,
      :"remote_id" => :query,
      :"team_id" => :query,
      :"work_location_id" => :query
    }
    %{}
    |> method(:get)
    |> url("/employees")
    |> add_param(:headers, :"Authorization", authorization)
    |> add_param(:headers, :"X-Account-Token", x_account_token)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %MergeHRISClient.Model.PaginatedEmployeeList{}}
    ])
  end

  @doc """
  Returns an `Employee` object with the given `id`.

  ## Parameters

  - connection (MergeHRISClient.Connection): Connection to server
  - authorization (String.t): Should include 'Bearer ' followed by your production API Key.
  - x_account_token (String.t): Token identifying the end user.
  - id (String.t): 
  - opts (KeywordList): [optional] Optional parameters
    - :expand (String.t): Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
    - :include_remote_data (boolean()): Whether to include the original data Merge fetched from the third-party to produce these models.
    - :include_sensitive_fields (boolean()): Whether to include sensetive fields (such as social security numbers) in the response.
  ## Returns

  {:ok, MergeHRISClient.Model.Employee.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec employees_retrieve(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, MergeHRISClient.Model.Employee.t} | {:error, Tesla.Env.t}
  def employees_retrieve(connection, authorization, x_account_token, id, opts \\ []) do
    optional_params = %{
      :"expand" => :query,
      :"include_remote_data" => :query,
      :"include_sensitive_fields" => :query
    }
    %{}
    |> method(:get)
    |> url("/employees/#{id}")
    |> add_param(:headers, :"Authorization", authorization)
    |> add_param(:headers, :"X-Account-Token", x_account_token)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %MergeHRISClient.Model.Employee{}}
    ])
  end
end
