# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Api.LinkedAccounts do
  @moduledoc """
  API calls for all endpoints tagged `LinkedAccounts`.
  """

  alias MergeHRISClient.Connection
  import MergeHRISClient.RequestBuilder


  @doc """
  List linked accounts for your organization.

  ## Parameters

  - connection (MergeHRISClient.Connection): Connection to server
  - authorization (String.t): Should include 'Bearer ' followed by your production API Key.
  - opts (KeywordList): [optional] Optional parameters
    - :category (String.t): 
    - :cursor (String.t): The pagination cursor value.
    - :end_user_email_address (String.t): 
    - :end_user_organization_name (String.t): 
    - :end_user_origin_id (String.t): 
    - :end_user_origin_ids (String.t): Comma-separated list of EndUser origin IDs, making it possible to specify multiple EndUsers at once
    - :id (String.t): 
    - :ids (String.t): Comma-separated list of LinkedAccount IDs, making it possible to specify multiple LinkedAccounts at once
    - :integration_name (String.t): 
    - :is_test_account (String.t): If included, will only include test linked accounts. If not included, will only include non-test linked accounts
    - :page_size (integer()): Number of results to return per page.
    - :status (String.t): Filter by status. Options: `COMPLETE`, `INCOMPLETE`, `RELINK_NEEDED`
  ## Returns

  {:ok, MergeHRISClient.Model.PaginatedAccountDetailsAndActionsList.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec linked_accounts_list(Tesla.Env.client, String.t, keyword()) :: {:ok, MergeHRISClient.Model.PaginatedAccountDetailsAndActionsList.t} | {:error, Tesla.Env.t}
  def linked_accounts_list(connection, authorization, opts \\ []) do
    optional_params = %{
      :"category" => :query,
      :"cursor" => :query,
      :"end_user_email_address" => :query,
      :"end_user_organization_name" => :query,
      :"end_user_origin_id" => :query,
      :"end_user_origin_ids" => :query,
      :"id" => :query,
      :"ids" => :query,
      :"integration_name" => :query,
      :"is_test_account" => :query,
      :"page_size" => :query,
      :"status" => :query
    }
    %{}
    |> method(:get)
    |> url("/linked-accounts")
    |> add_param(:headers, :"Authorization", authorization)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %MergeHRISClient.Model.PaginatedAccountDetailsAndActionsList{}}
    ])
  end
end
