# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Api.LinkToken do
  @moduledoc """
  API calls for all endpoints tagged `LinkToken`.
  """

  alias MergeHRISClient.Connection
  import MergeHRISClient.RequestBuilder


  @doc """
  Creates a link token to be used when linking a new end user.

  ## Parameters

  - connection (MergeHRISClient.Connection): Connection to server
  - authorization (String.t): Should include 'Bearer ' followed by your test/production API Key.
  - end_user_details_request (EndUserDetailsRequest):
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, MergeHRISClient.Model.LinkToken.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec link_token_create(Tesla.Env.client, String.t, MergeHRISClient.Model.EndUserDetailsRequest.t, keyword()) :: {:ok, MergeHRISClient.Model.LinkToken.t} | {:error, Tesla.Env.t}
  def link_token_create(connection, authorization, end_user_details_request, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/link-token")
    |> add_param(:headers, :"Authorization", authorization)
    |> add_param(:body, :body, end_user_details_request)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %MergeHRISClient.Model.LinkToken{}}
    ])
  end
end
