# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Api.RegenerateKey do
  @moduledoc """
  API calls for all endpoints tagged `RegenerateKey`.
  """

  alias MergeHRISClient.Connection
  import MergeHRISClient.RequestBuilder


  @doc """
  Exchange remote keys.

  ## Parameters

  - connection (MergeHRISClient.Connection): Connection to server
  - authorization (String.t): Should include 'Bearer ' followed by your production API Key.
  - remote_key_for_regeneration_request (RemoteKeyForRegenerationRequest): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, MergeHRISClient.Model.RemoteKey.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec regenerate_key_create(Tesla.Env.client, String.t, MergeHRISClient.Model.RemoteKeyForRegenerationRequest.t, keyword()) :: {:ok, MergeHRISClient.Model.RemoteKey.t} | {:error, Tesla.Env.t}
  def regenerate_key_create(connection, authorization, remote_key_for_regeneration_request, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/regenerate-key")
    |> add_param(:headers, :"Authorization", authorization)
    |> add_param(:body, :body, remote_key_for_regeneration_request)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %MergeHRISClient.Model.RemoteKey{}}
    ])
  end
end
