# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Model.AccountToken do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"account_token",
    :"integration"
  ]

  @type t :: %__MODULE__{
    :"account_token" => String.t,
    :"integration" => MergeHRISClient.Model.AccountIntegration.t
  }
end

defimpl Poison.Decoder, for: MergeHRISClient.Model.AccountToken do
  import MergeHRISClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"integration", :struct, MergeHRISClient.Model.AccountIntegration, options)
  end
end

