# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Model.AvailableActions do
  @moduledoc """
  # The AvailableActions Object ### Description The `Activity` object is used to see all available model/operation combinations for an integration.  ### Usage Example Fetch all the actions available for the `Zenefits` integration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"integration",
    :"passthrough_available",
    :"available_model_operations"
  ]

  @type t :: %__MODULE__{
    :"integration" => MergeHRISClient.Model.AccountIntegration.t,
    :"passthrough_available" => boolean(),
    :"available_model_operations" => [MergeHRISClient.Model.ModelOperation.t] | nil
  }
end

defimpl Poison.Decoder, for: MergeHRISClient.Model.AvailableActions do
  import MergeHRISClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"integration", :struct, MergeHRISClient.Model.AccountIntegration, options)
    |> deserialize(:"available_model_operations", :list, MergeHRISClient.Model.ModelOperation, options)
  end
end

