# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Model.BenefitRequest do
  @moduledoc """
  # The Benefit Object ### Description The `Benefit` object is used to represent a Benefit for an employee.  ### Usage Example Fetch from the `LIST Benefits` endpoint and filter by `ID` to show all benefits.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"remote_id",
    :"employee",
    :"provider_name",
    :"benefit_plan_type",
    :"employee_contribution",
    :"company_contribution"
  ]

  @type t :: %__MODULE__{
    :"remote_id" => String.t | nil,
    :"employee" => String.t | nil,
    :"provider_name" => String.t | nil,
    :"benefit_plan_type" => BenefitPlanTypeEnum | nil,
    :"employee_contribution" => float() | nil,
    :"company_contribution" => float() | nil
  }
end

defimpl Poison.Decoder, for: MergeHRISClient.Model.BenefitRequest do
  import MergeHRISClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"benefit_plan_type", :struct, MergeHRISClient.Model.BenefitPlanTypeEnum, options)
  end
end

