# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Model.DataPassthroughRequest do
  @moduledoc """
  # The DataPassthrough Object ### Description The `DataPassthrough` object is used to send information to an otherwise-unsupported third-party endpoint.  ### Usage Example Create a `DataPassthrough` to get team hierarchies from your Rippling integration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"method",
    :"path",
    :"base_url_override",
    :"data",
    :"multipart_form_data",
    :"headers",
    :"request_format",
    :"normalize_response"
  ]

  @type t :: %__MODULE__{
    :"method" => MethodEnum,
    :"path" => String.t,
    :"base_url_override" => String.t | nil,
    :"data" => String.t | nil,
    :"multipart_form_data" => [MergeHRISClient.Model.MultipartFormFieldRequest.t] | nil,
    :"headers" => %{optional(String.t) => :any} | nil,
    :"request_format" => RequestFormatEnum | nil,
    :"normalize_response" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: MergeHRISClient.Model.DataPassthroughRequest do
  import MergeHRISClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"method", :struct, MergeHRISClient.Model.MethodEnum, options)
    |> deserialize(:"multipart_form_data", :list, MergeHRISClient.Model.MultipartFormFieldRequest, options)
    |> deserialize(:"headers", :map, MergeHRISClient.Model.RemoteData, Keyword.merge(options, [as: :any]))
    |> deserialize(:"request_format", :struct, MergeHRISClient.Model.RequestFormatEnum, options)
  end
end
