# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Model.Deduction do
  @moduledoc """
  # The Deduction Object ### Description The `Deduction` object is used to represent a deduction for a given employee's payroll run. One run could include several deductions.  ### Usage Example Fetch from the `LIST Deductions` endpoint and filter by `ID` to show all deductions.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"employee_payroll_run",
    :"name",
    :"employee_deduction",
    :"company_deduction",
    :"remote_data"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"employee_payroll_run" => String.t | nil,
    :"name" => String.t | nil,
    :"employee_deduction" => float() | nil,
    :"company_deduction" => float() | nil,
    :"remote_data" => [%{optional(String.t) => AnyType}] | nil
  }
end

defimpl Poison.Decoder, for: MergeHRISClient.Model.Deduction do
  def decode(value, _options) do
    value
  end
end

