# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Model.EmploymentRequest do
  @moduledoc """
  # The Employment Object ### Description The `Employment` object is used to represent an employment position at a company. These are associated with the employee filling the role.  ### Usage Example Fetch from the `LIST Employments` endpoint and filter by `ID` to show all employees.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"remote_id",
    :"job_title",
    :"pay_rate",
    :"pay_period",
    :"pay_frequency",
    :"pay_currency",
    :"flsa_status",
    :"effective_date",
    :"employment_type"
  ]

  @type t :: %__MODULE__{
    :"remote_id" => String.t | nil,
    :"job_title" => String.t | nil,
    :"pay_rate" => float() | nil,
    :"pay_period" => PayPeriodEnum | nil,
    :"pay_frequency" => PayFrequencyEnum | nil,
    :"pay_currency" => PayCurrencyEnum | nil,
    :"flsa_status" => FlsaStatusEnum | nil,
    :"effective_date" => DateTime.t | nil,
    :"employment_type" => EmploymentTypeEnum | nil
  }
end

defimpl Poison.Decoder, for: MergeHRISClient.Model.EmploymentRequest do
  import MergeHRISClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"pay_period", :struct, MergeHRISClient.Model.PayPeriodEnum, options)
    |> deserialize(:"pay_frequency", :struct, MergeHRISClient.Model.PayFrequencyEnum, options)
    |> deserialize(:"pay_currency", :struct, MergeHRISClient.Model.PayCurrencyEnum, options)
    |> deserialize(:"flsa_status", :struct, MergeHRISClient.Model.FlsaStatusEnum, options)
    |> deserialize(:"employment_type", :struct, MergeHRISClient.Model.EmploymentTypeEnum, options)
  end
end

