# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Model.EmployeePayrollRun do
  @moduledoc """
  # The EmployeePayrollRun Object ### Description The `EmployeePayrollRun` object is used to represent a payroll run for a specific employee.  ### Usage Example Fetch from the `LIST EmployeePayrollRun` endpoint and filter by `ID` to show all employee payroll runs.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"employee",
    :"payroll_run",
    :"gross_pay",
    :"net_pay",
    :"start_date",
    :"end_date",
    :"check_date",
    :"earnings",
    :"deductions",
    :"taxes",
    :"remote_data",
    :"remote_was_deleted"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"employee" => String.t | nil,
    :"payroll_run" => String.t | nil,
    :"gross_pay" => float() | nil,
    :"net_pay" => float() | nil,
    :"start_date" => DateTime.t | nil,
    :"end_date" => DateTime.t | nil,
    :"check_date" => DateTime.t | nil,
    :"earnings" => [MergeHRISClient.Model.Earning.t] | nil,
    :"deductions" => [MergeHRISClient.Model.Deduction.t] | nil,
    :"taxes" => [MergeHRISClient.Model.Tax.t] | nil,
    :"remote_data" => [MergeHRISClient.Model.RemoteData.t] | nil,
    :"remote_was_deleted" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: MergeHRISClient.Model.EmployeePayrollRun do
  import MergeHRISClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"earnings", :list, MergeHRISClient.Model.Earning, options)
    |> deserialize(:"deductions", :list, MergeHRISClient.Model.Deduction, options)
    |> deserialize(:"taxes", :list, MergeHRISClient.Model.Tax, options)
    |> deserialize(:"remote_data", :list, MergeHRISClient.Model.RemoteData, options)
  end
end

