# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Model.EndUserDetailsRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"end_user_email_address",
    :"end_user_organization_name",
    :"end_user_origin_id",
    :"categories",
    :"integration",
    :"link_expiry_mins"
  ]

  @type t :: %__MODULE__{
    :"end_user_email_address" => String.t,
    :"end_user_organization_name" => String.t,
    :"end_user_origin_id" => String.t,
    :"categories" => [MergeHRISClient.Model.CategoriesEnum.t],
    :"integration" => String.t | nil,
    :"link_expiry_mins" => integer() | nil
  }
end

defimpl Poison.Decoder, for: MergeHRISClient.Model.EndUserDetailsRequest do
  import MergeHRISClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"categories", :list, MergeHRISClient.Model.CategoriesEnum, options)
  end
end

