# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Model.IgnoreCommonModel do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"reason",
    :"message"
  ]

  @type t :: %__MODULE__{
    :"reason" => ReasonEnum,
    :"message" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MergeHRISClient.Model.IgnoreCommonModel do
  import MergeHRISClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"reason", :struct, MergeHRISClient.Model.ReasonEnum, options)
  end
end

