# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Model.LinkedAccountStatus do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"linked_account_status",
    :"can_make_request"
  ]

  @type t :: %__MODULE__{
    :"linked_account_status" => String.t,
    :"can_make_request" => boolean()
  }
end

defimpl Poison.Decoder, for: MergeHRISClient.Model.LinkedAccountStatus do
  def decode(value, _options) do
    value
  end
end

