# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Model.Location do
  @moduledoc """
  # The Location Object ### Description The `Location` object is used to represent a Location for a Company or Employee address. This is shared across many models and is referenced whenever a location is stored.  ### Usage Example Fetch from the `LIST Locations` endpoint and filter by `ID` to show all office locations.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"remote_id",
    :"name",
    :"phone_number",
    :"street_1",
    :"street_2",
    :"city",
    :"state",
    :"zip_code",
    :"country",
    :"location_type",
    :"remote_data",
    :"remote_was_deleted"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"remote_id" => String.t | nil,
    :"name" => String.t | nil,
    :"phone_number" => String.t | nil,
    :"street_1" => String.t | nil,
    :"street_2" => String.t | nil,
    :"city" => String.t | nil,
    :"state" => String.t | nil,
    :"zip_code" => String.t | nil,
    :"country" => CountryEnum | nil,
    :"location_type" => LocationTypeEnum | nil,
    :"remote_data" => [MergeHRISClient.Model.RemoteData.t] | nil,
    :"remote_was_deleted" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: MergeHRISClient.Model.Location do
  import MergeHRISClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"country", :struct, MergeHRISClient.Model.CountryEnum, options)
    |> deserialize(:"location_type", :struct, MergeHRISClient.Model.LocationTypeEnum, options)
    |> deserialize(:"remote_data", :list, MergeHRISClient.Model.RemoteData, options)
  end
end

