# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MergeHRISClient.Model.TimeOffEndpointRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"model"
  ]

  @type t :: %__MODULE__{
    :"model" => MergeHRISClient.Model.TimeOffRequest.t
  }
end

defimpl Poison.Decoder, for: MergeHRISClient.Model.TimeOffEndpointRequest do
  import MergeHRISClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"model", :struct, MergeHRISClient.Model.TimeOffRequest, options)
  end
end

